import getpass
import smtplib
from email.mime.text import MIMEText
import re

# Test just the email sending part
print("📧 Testing Email Body with Articles")
print("=" * 50)

# Get Gmail App Password
gmail_password = getpass.getpass("Enter Gmail App Password for yourfriendlyintern1@gmail.com: ")

# Sample articles (like what we get from Tavily)
articles = [
    {
        "title": "Washington, DC News - WTOP",
        "url": "https://wtop.com/local/dc/",
        "content": "DC's top news source for breaking coverage of local stories, weather and traffic. Stay on top of what's happening in Washington, DC with WTOP's news team."
    },
    {
        "title": "WTOP | Washington's Top News | DC, MD & VA News, Traffic",
        "url": "https://wtop.com/",
        "content": "WTOP delivers the latest news, traffic and weather information to the Washington, D.C. region. See today's top stories."
    },
    {
        "title": "Washington, DC's Leading Local News: Weather, Traffic, Sports",
        "url": "https://www.wusa9.com/",
        "content": "WUSA9.com is the official website for WUSA-TV, your trusted source for breaking news, weather and sports in Washington, D.C.."
    }
]

# Create email content with articles as the main body
subject = "Washington DC News Update"
from_email = "yourfriendlyintern1@gmail.com"
recipients = ["zmh4616@vt.edu", "bbgold24@vt.edu"]
to_email = ", ".join(recipients)

# Build email content with articles as the main body
email_content = f"""Washington DC News Update
{'='*50}

Here are the top Washington DC news stories for today:

"""

# Add each article with full content as the main body
for i, article in enumerate(articles, 1):
    title = re.sub(r'[^\x00-\x7F]+', '', article.get('title', 'No title'))
    url = article.get('url', '#')
    content = re.sub(r'[^\x00-\x7F]+', '', article.get('content', 'No content available'))
    
    email_content += f"""
ARTICLE {i}: {title}
{'='*60}
{content}

Read more: {url}

"""

email_content += f"""
{'='*50}
This email was generated by an automated multi-agent system.
For questions, contact: {from_email}
"""

print(f"📧 Email Content Preview:")
print("=" * 50)
print(email_content[:500] + "..." if len(email_content) > 500 else email_content)
print("=" * 50)

# Clean the Gmail password
clean_password = gmail_password.encode('ascii', 'ignore').decode('ascii')

# Try to send via Gmail
try:
    print(f"\n🚀 Attempting to send email...")
    msg = MIMEText(email_content, 'utf-8')
    msg['Subject'] = subject
    msg['From'] = from_email
    msg['To'] = to_email
    
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(from_email, clean_password)
        server.send_message(msg)
    
    print("✅ Email sent successfully!")
    print("📧 Check the recipients' inboxes!")
    print("📰 Articles should be in the email body, not as attachments!")
    print(f"Recipients: {', '.join(recipients)}")
    
except smtplib.SMTPAuthenticationError as e:
    print(f"❌ Gmail Authentication Error: {e}")
    print("💡 Try regenerating your Gmail App Password")
    
except Exception as e:
    print(f"❌ Error sending email: {e}")
    print(f"Error type: {type(e).__name__}")

print("\n" + "=" * 50)
print("Email test complete!")
